In [12]:
# http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html
import numpy as np

In [2]:
# The way of python

In [3]:
Z = [[0,0,0,0,0,0],
     [0,0,0,1,0,0],
     [0,1,0,1,0,0],
     [0,0,1,1,0,0],
     [0,0,0,0,0,0],
     [0,0,0,0,0,0]]

In [4]:
def compute_neighbors(Z):
  shape = len(Z), len(Z[0])
  N = [[0,]*shape[0] for i in range(shape[1])]
  for x in range(1,shape[0]-1):
    for y in range(1, shape[1]-1):
      N[x][y] = Z[x-1][y-1]+Z[x][y-1]+Z[x+1][y-1] \
                + Z[x-1][y]            +Z[x+1][y]   \
                + Z[x-1][y+1]+Z[x][y+1]+Z[x+1][y+1]
  return N

In [5]:
def iterate(Z):
  N = compute_neighbors(Z)
  shape = len(Z), len(Z[0])
  for x in range(1,shape[0]-1):
    for y in range(1, shape[1]-1):
      if Z[x][y] == 1 and (N[x][y] < 2 or N[x][y] > 3):
        Z[x][y] = 0
      elif Z[x][y] == 0 and N[x][y] == 3:
        Z[x][y] = 1
  return Z

In [8]:
def show(Z):
    for l in Z[1:-1]: print(l[1:-1])
    print()
show(Z)

[0, 0, 1, 0]
[1, 0, 1, 0]
[0, 1, 1, 0]
[0, 0, 0, 0]



In [10]:
for i in range(4):
  iterate(Z)
  show(Z)

[0, 0, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]
[0, 0, 1, 1]

[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 1]

[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 1, 1]
[0, 0, 1, 1]

[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 1, 1]
[0, 0, 1, 1]



In [11]:
# The way of numpy

In [13]:
Z = np.array([[0,0,0,0,0,0],
     [0,0,0,1,0,0],
     [0,1,0,1,0,0],
     [0,0,1,1,0,0],
     [0,0,0,0,0,0],
     [0,0,0,0,0,0]])

In [14]:
print(Z[1:-1,1:-1])

[[0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 0]]
